import{a as b,S,i as s}from"./assets/vendor-lDhL-8I6.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const l of r.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&c(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function c(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();const v="https://pixabay.com/api/",q="42434028-6957339565ff307ea1e8da0af";async function m(n,e=1){const o={key:q,q:n,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15};return(await b.get(v,{params:o})).data}const f=document.querySelector(".gallery"),g=document.querySelector("#loader"),p=document.querySelector("#load-more-btn");let R=new S(".gallery a",{captionsData:"alt",captionDelay:250});function h(n){const e=n.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" />
      </a>
      <div class="info">
        <p><strong>Likes</strong><br>${o.likes}</p>
        <p><strong>Views</strong><br>${o.views}</p>
        <p><strong>Comments</strong><br>${o.comments}</p>
        <p><strong>Downloads</strong><br>${o.downloads}</p>
      </div>
    </li>
    `).join("");f.insertAdjacentHTML("beforeend",e),R.refresh()}function B(){f.innerHTML=""}function y(){g.classList.remove("hidden")}function L(){g.classList.add("hidden")}function w(){p.classList.remove("hidden")}function d(){p.classList.add("hidden")}const $=document.querySelector(".form"),M=document.querySelector('input[name="search-text"]'),I=document.querySelector("#load-more-btn");let a="",i=1,u=0;$.addEventListener("submit",async n=>{if(n.preventDefault(),a=M.value.trim(),a===""){s.error({message:"Please enter a search term!",position:"topRight"});return}i=1,B(),d(),y();try{const e=await m(a,i);if(u=e.totalHits,e.hits.length===0){s.info({message:"Sorry, there are no images matching your search query.",position:"topRight"});return}h(e.hits),u>15&&w()}catch(e){s.error({message:"Something went wrong. Try again later.",position:"topRight"}),console.error(e)}finally{L()}});I.addEventListener("click",async()=>{i+=1,y(),d();try{const n=await m(a,i);h(n.hits);const{height:e}=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"}),document.querySelectorAll(".gallery-item").length>=u?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):w()}catch{s.error({message:"Something went wrong. Try again later.",position:"topRight"})}finally{L()}});
//# sourceMappingURL=index.js.map
